# Generated by Django 3.1.5 on 2021-01-31 06:58

from django.db import migrations, models
import django.db.models.deletion
import pokemons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('types', models.JSONField(default=pokemons.models.get_default_something)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemons.pokemon')),
            ],
        ),
    ]
